### ISSUE TITLE
Error with Database Connection

### ISSUE THREAD

**Issue by Grenk** [Itsyuka/Altis-Life#89] opened 2015-03-29 00:38 UTC
2015/03/29,  1:37:59 "extDB: Version: 35"
2015/03/29,  1:37:59 "extDB: Error with Database Connection"

**Comment by hitem** [comment] 2015-03-29 13:55
thats 99% a local issue and nothing wrong with Altis Life.
Make sure you have named the database correct (AltisLife) and that you can access it via any sql tool (like navicat). else you need to make a post on altis life rpg forum for more help and with loggs (extdb etc).  As connection is confirmed and working for current build.

**Comment by Grenk** [comment] 2015-03-30 21:09
If it works perfectly database, Altis this version does not work but with this if https://github.com/TAWTonic/Altis-Life

**Comment by Grenk** [comment] 2015-03-30 21:10
[23:08:11 +02:00] [Thread 2922841770] extDB: Version: 35
[23:08:11 +02:00] [Thread 2922841770] extDB: Windows Version
[23:08:11 +02:00] [Thread 2922841770] Message: Arma Linux Servers are using Older Physic Library (than Windows Servers), due to Debian 7 using old version of Glibc
[23:08:11 +02:00] [Thread 2922841770] Message: If you like extDB consider donating or bug BIS to drop support for Debian 7 thanks, so Linux Servers get same Physic Library Version as Windows
[23:08:11 +02:00] [Thread 2922841770] Message: Note currently most/all development for extDB is done on a Linux Server
[23:08:11 +02:00] [Thread 2922841770] Message: Torndeco: 24/01/15
[23:08:11 +02:00] [Thread 2922841770] 
[23:08:11 +02:00] [Thread 2922841770] extDB: Found extdb-conf.ini
[23:08:11 +02:00] [Thread 2922841770] extDB: Detected 8 Cores, Setting up 6 Worker Threads
[23:08:11 +02:00] [Thread 2922841770] extDB: No Config Option Found: AltisLife
[23:09:51 +02:00] [Thread 2922841770] extDB: Stopping ...

**Comment by hitem** [comment] 2015-03-31 13:33
Yeah, as mention earlier, you have to name your database "AltisLife" in extdbcfg (clearly stated in the error)
[23:08:11 +02:00] [Thread 2922841770] extDB: No Config Option Found: AltisLife

**Comment by Grenk** [comment] 2015-03-31 17:04
I put Database2 but still not working:
[Database2]
;; Example of MySQL
;; 	AtlisLifeRPG uses Database2 by default
Type = MySQL
Name = arma3life

Username = root
Password = password
IP = 127.0.0.1
Port = 3306

minSessions = 1
;maxSessions = 4
idleTime = 60

compress = false
; Should only use this if MySQL server is external. Also only for MySQL

Secure Auth = false
; Recommend you turn this on

extDB Log:

[18:59:56 +02:00] [Thread 1393633123] extDB: Version: 35
[18:59:56 +02:00] [Thread 1393633123] extDB: Windows Version
[18:59:56 +02:00] [Thread 1393633123] Message: Arma Linux Servers are using Older Physic Library (than Windows Servers), due to Debian 7 using old version of Glibc
[18:59:56 +02:00] [Thread 1393633123] Message: If you like extDB consider donating or bug BIS to drop support for Debian 7 thanks, so Linux Servers get same Physic Library Version as Windows
[18:59:56 +02:00] [Thread 1393633123] Message: Note currently most/all development for extDB is done on a Linux Server
[18:59:56 +02:00] [Thread 1393633123] Message: Torndeco: 24/01/15
[18:59:56 +02:00] [Thread 1393633123] 
[18:59:56 +02:00] [Thread 1393633123] extDB: Found extdb-conf.ini
[18:59:56 +02:00] [Thread 1393633123] extDB: Detected 8 Cores, Setting up 6 Worker Threads
[18:59:56 +02:00] [Thread 1393633123] extDB: No Config Option Found: AltisLife
[19:00:50 +02:00] [Thread 1393633123] extDB: Stopping ...

**Comment by SaurusMaster** [comment] 2015-03-31 18:22
Change [Database2] to [AltisLife]

**Comment by Grenk** [comment] 2015-03-31 21:34
Does not work  SaurusMaster

**Comment by hitem** [comment] 2015-03-31 23:51
Can you connect to your SQL locally and check all the tables? If so, post the logg of what its saying when you have 'AltisLife' as the name.
As of now we have only seen the same issue with the same results.

**Comment by Grenk** [comment] 2015-04-01 17:15
Image: [IMG]http://i61.tinypic.com/10hua68.jpg[/IMG]

**Comment by Grenk** [comment] 2015-04-01 17:21
Image 2:
http://i59.tinypic.com/2af08ww.jpg

**Comment by Grenk** [comment] 2015-04-01 17:27
You can add me to steam hitem?

if I pay solves

**Comment by SaurusMaster** [comment] 2015-04-01 18:03
have you a log from extdb? ...\Arma 3\@extDB\extDB\logs\2015\4\01 for example

**Comment by SaurusMaster** [comment] 2015-04-01 18:43
Have change the extDB Log now? (an other erro)

**Comment by Grenk** [comment] 2015-04-01 20:00
[19:02:09 +02:00] [Thread 1903175579] extDB: Version: 35
[19:02:09 +02:00] [Thread 1903175579] extDB: Windows Version
[19:02:09 +02:00] [Thread 1903175579] Message: Arma Linux Servers are using Older Physic Library (than Windows Servers), due to Debian 7 using old version of Glibc
[19:02:09 +02:00] [Thread 1903175579] Message: If you like extDB consider donating or bug BIS to drop support for Debian 7 thanks, so Linux Servers get same Physic Library Version as Windows
[19:02:09 +02:00] [Thread 1903175579] Message: Note currently most/all development for extDB is done on a Linux Server
[19:02:09 +02:00] [Thread 1903175579] Message: Torndeco: 24/01/15
[19:02:09 +02:00] [Thread 1903175579] 
[19:02:09 +02:00] [Thread 1903175579] extDB: Found extdb-conf.ini
[19:02:09 +02:00] [Thread 1903175579] extDB: Detected 8 Cores, Setting up 6 Worker Threads
[19:02:09 +02:00] [Thread 1903175579] extDB: No Config Option Found: AltisLife
[19:05:23 +02:00] [Thread 1903175579] extDB: Stopping ...

**Comment by SaurusMaster** [comment] 2015-04-01 20:26
ok, delete your extdb-conf.ini and download again from github, It maybe an invisible symbol and extdb can`t read this.

**Comment by Grenk** [comment] 2015-04-02 20:11
Not working :(
Gives the same error.

You can connect by team viewer??
If you solve me I will pay by paypal

**Comment by SaurusMaster** [comment] 2015-04-02 21:02
You can me add by steam: |EGE|SaurusMaster

**Comment by Grenk** [comment] 2015-04-02 21:29
I've already sent, my name is Aiittor

**Comment by FisherSam** [comment] 2015-04-04 07:00
HI! I have exactly the same problem as in Grenk, tell me how you solved it?

Thanks you in advance/

**Comment by FisherSam** [comment] 2015-04-04 08:01
That is, it is necessary in the config extdb-conf.ini leave only that, but to remove all unnecessary:

[Main]
;Threads = 0  
; Default Value is the number of CPU Cores Detected (max value is 6, min value is 2)
; Linux Chroot Environment might only Detect 1 CPU Cores i.e bind /proc

Randomize Config File = false
;This is a legacy option to randomize config file for Arma2 Servers.


[Rcon]
;; This is functional, should be working fine. Just needs abit of testing on a live Server

Port = 2302
Password = 4564jnd67rnbjt68


[Steam]
;; This is for VAC Protocol for VAC Bans + Steam Friends.
;; This currently has a bug in it, will be fixed next version.
;; Think of it as tech preview option.
;; https://steamcommunity.com/dev/apikey
API Key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


[VAC]
;; This feature requires Steam + Rcon to be enabled.
;; Also this feature is called via SQF Code atm, i.e it doesn't auto detect players joining server yet....

Auto Ban = false

;; For Player to get banned ( their total VAC Bans => NumberOfVACBans)  AND ( Days Since their Last Ban was <= DaysSinceLastBan)
;; This is also used extDB Protocol VAC:VACBanned returned results
NumberOfVACBans = 1
DaysSinceLastBan = 999999999

BanDuration = 0
;; 0 = Forever, otherwise its x Minutes
BanMessage = Steam VAC Banned


[Log]
;; This is just config options for Rcon Logging + BE Logging
;;		Has no effect on extDB Logging
Mode = sync
;; sync / async
;;	ASync is just kinder on your Harddrive, may be lose of data in the event of a crash.


[AltisLife]
;; Example of MySQL
;; 	AtlisLifeRPG uses Database2 by default
Type = MySQL
Name = any database name

Username = any name
Password = 68Iun889b967yni7yj985b
IP = localhost
Port = 3306

minSessions = 1
;maxSessions = 4
idleTime = 60

compress = false
; Should only use this if MySQL server is external. Also only for MySQL

Secure Auth = false
; Recommend you turn this on

**Comment by SaurusMaster** [comment] 2015-04-05 22:10
put your  extdb-conf.ini in @extdb

**Closed** 2015-05-06 17:14 UTC
